import { RouletteBetCategory } from "../types/RouletteBetCategory.ts";

import type { RouletteBetCategoryConfig } from "../types/RouletteBetCategoryConfig.ts";

export const ROULETTE_BET_CATEGORIES: RouletteBetCategoryConfig[] = [
  {
    category: RouletteBetCategory.COLOR,
    label: 'Color',
    description: 'Bet on red or black (Payout: 1:1)',
    emoji: '🔴',
    requiresTarget: true,
    targetType: 'FIXED',
    enabled: true,
  },
  {
    category: RouletteBetCategory.EVEN_ODD,
    label: 'Even / Odd',
    description: 'Bet on even or odd (Payout: 1:1)',
    emoji: '➗',
    requiresTarget: true,
    targetType: 'FIXED',
    enabled: true,
  },
  {
    category: RouletteBetCategory.LOW_HIGH,
    label: 'High / Low',
    description: 'Bet on high (19-36) or low (1-18) (Payout: 1:1)',
    emoji: '⬆️',
    requiresTarget: true,
    targetType: 'FIXED',
    enabled: true,
  },
  {
    category: RouletteBetCategory.DOZEN,
    label: 'Dozens',
    description: "Bet by 12's (Payout: 2:1)",
    emoji: '🔢',
    requiresTarget: true,
    targetType: 'FIXED',
    enabled: true,
  },
  {
    category: RouletteBetCategory.COLUMN,
    label: 'Column',
    description: 'Bet by columns (Payout: 2:1)',
    emoji: '🧱',
    requiresTarget: true,
    targetType: 'FIXED',
    enabled: true,
  },
  {
    category: RouletteBetCategory.DOUBLE_STREET,
    label: 'Double Street',
    description: 'Bet on 6 consecutive numbers (Payout: 5:1)',
    emoji: '🛣️',
    requiresTarget: true,
    targetType: 'DROPDOWN',
    enabled: true,
  },
  {
    category: RouletteBetCategory.TOP_LINE,
    label: 'Top Line',
    description: 'Bet on 0, 00, 1, 2, and 3 (Payout: 6:1)',
    emoji: '🎯',
    requiresTarget: false,
    targetType: 'STATIC',
    enabled: true,
  },
  {
    label: 'Corner',
    category: RouletteBetCategory.CORNER,
    description: 'Bet on 4 numbers (Payout: 8:1)',
    emoji: '📐',
    requiresTarget: true,
    targetType: 'DROPDOWN',
    enabled: true,
  },
  {
    category: RouletteBetCategory.STREET,
    label: 'Street',
    description: 'Bet on 3 consecutive numbers (Payout: 11:1)',
    emoji: '🛤️',
    requiresTarget: true,
    targetType: 'DROPDOWN',
    enabled: true,
  },
  {
    category: RouletteBetCategory.ROW,
    label: 'Row',
    description: 'Bet on 0 and 00 (Payout: 17:1)',
    emoji: '🧩',
    requiresTarget: false,
    targetType: 'STATIC',
    enabled: true,
  },
  {
    category: RouletteBetCategory.SPLIT,
    label: 'Split',
    description: 'Bet on two adjacent numbers (Payout: 17:1)',
    emoji: '✂️',
    requiresTarget: true,
    targetType: 'SPLIT',
    enabled: true,
  },
  {
    category: RouletteBetCategory.NUMBER,
    label: 'Single Number',
    description: 'Bet on a single number (Payout: 35:1)',
    emoji: '🎲',
    requiresTarget: true,
    targetType: 'NUMBER_INPUT',
    enabled: true,
  },
];
